root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  args_bin = []
  bin = "./bin/prservice"
  cmd = "make"
  delay = 1000
  exclude_dir = ["static", "assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  log = "build-errors.log"

[misc]
  clean_on_exit = true 

[screen]
  clear_on_rebuild = false 
  keep_scroll = true
