services:
  prservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prservice
    ports:
      - 8080:80/tcp
    volumes:
      - ./prservice.yaml:/etc/prservice/prservice.yaml
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:18
    container_name: prservice_postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prservice_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 3
  adminer:
    image: adminer:latest
    container_name: prservice_adminer
    ports:
      - 8081:8080/tcp
    environment:
      ADMINER_DEFAULT_SERVER: prservice_postgres
    depends_on:
      postgres:
        condition: service_healthy
  swagger-downloader:
    image: busybox:latest
    container_name: prservice_swagger_downloader
    command:
      - /bin/sh
      - -c
      - mkdir -p /spec && wget -O /spec/openapi.yaml http://prservice/static/openapi.yaml
    volumes:
      - swagger_spec:/spec
    depends_on:
      prservice:
        condition: service_healthy
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui:latest
    container_name: prservice_swagger
    ports:
      - 8082:8080/tcp
    environment:
      SWAGGER_JSON: /spec/openapi.yaml
    volumes:
      - swagger_spec:/spec
    depends_on:
      swagger-downloader:
        condition: service_completed_successfully

volumes:
  postgres_data: {}
  swagger_spec: {}
